// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Treinamentos.Infrastructure.Data;

#nullable disable

namespace Treinamentos.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Treinamentos.Domain.Entities.ActivationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsInvalidated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_invalidated");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_activation_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("i_x_activation_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_activation_tokens_user_id");

                    b.ToTable("activation_tokens");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_audit_logs");

                    b.HasIndex("Action")
                        .HasDatabaseName("i_x_audit_logs_action");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_audit_logs_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_audit_logs_user_id");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_categories");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("i_x_categories_parent_category_id");

                    b.HasIndex("Name", "ParentCategoryId")
                        .IsUnique()
                        .HasDatabaseName("i_x_categories_name_parent_category_id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Empresa")
                        .HasColumnType("integer")
                        .HasColumnName("empresa");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<int>("Revenda")
                        .HasColumnType("integer")
                        .HasColumnName("revenda");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_companies");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("i_x_companies_cnpj");

                    b.HasIndex("Empresa", "Revenda")
                        .IsUnique()
                        .HasDatabaseName("i_x_companies_empresa_revenda");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AvailableForAllCompanies")
                        .HasColumnType("boolean")
                        .HasColumnName("available_for_all_companies");

                    b.Property<bool>("AvailableForAllDepartments")
                        .HasColumnType("boolean")
                        .HasColumnName("available_for_all_departments");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uuid")
                        .HasColumnName("instructor_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SubCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_category_id");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_courses");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("i_x_courses_category_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("i_x_courses_company_id");

                    b.HasIndex("InstructorId")
                        .HasDatabaseName("i_x_courses_instructor_id");

                    b.HasIndex("SubCategoryId")
                        .HasDatabaseName("i_x_courses_sub_category_id");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.CourseApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Decision")
                        .HasColumnType("integer")
                        .HasColumnName("decision");

                    b.HasKey("Id")
                        .HasName("p_k_course_approvals");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("i_x_course_approvals_admin_id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("i_x_course_approvals_course_id");

                    b.ToTable("course_approvals");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.CourseCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_course_completions");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("i_x_course_completions_course_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_course_completions_user_id");

                    b.ToTable("course_completions");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.CourseDepartmentPermission", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.HasKey("CourseId", "Department")
                        .HasName("p_k_course_department_permissions");

                    b.ToTable("course_department_permissions");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.CourseUserPermission", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.HasKey("CourseId", "UserId")
                        .HasName("p_k_course_user_permissions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_course_user_permissions_user_id");

                    b.ToTable("course_user_permissions");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_departments");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_departments_name");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHtml")
                        .HasColumnType("text")
                        .HasColumnName("content_html");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("VideoDurationSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("video_duration_seconds");

                    b.Property<string>("VideoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("video_path");

                    b.HasKey("Id")
                        .HasName("p_k_lessons");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("i_x_lessons_course_id");

                    b.ToTable("lessons");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.LessonAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accessed_at");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_lesson_accesses");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("i_x_lesson_accesses_lesson_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_lesson_accesses_user_id");

                    b.ToTable("lesson_accesses");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.RevokedToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("p_k_revoked_tokens");

                    b.ToTable("revoked_tokens");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("google_id");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_title");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("i_x_users_company_id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_cpf");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("login_at");

                    b.Property<DateTime?>("LogoutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logout_at");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_sessions_user_id");

                    b.ToTable("user_sessions");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.VideoProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("FirstAccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_access_at");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<long>("LastSecond")
                        .HasColumnType("bigint")
                        .HasColumnName("last_second");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<decimal>("PercentageWatched")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentage_watched");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("ViewSessions")
                        .HasColumnType("integer")
                        .HasColumnName("view_sessions");

                    b.HasKey("Id")
                        .HasName("p_k_video_progresses");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("i_x_video_progresses_lesson_id");

                    b.HasIndex("UserId", "LessonId")
                        .IsUnique()
                        .HasDatabaseName("i_x_video_progresses_user_id_lesson_id");

                    b.ToTable("video_progresses");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.ActivationToken", b =>
                {
                    b.HasOne("Treinamentos.Domain.Entities.User", "User")
                        .WithMany("ActivationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_activation_tokens__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Treinamentos.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_audit_logs__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.Category", b =>
                {
                    b.HasOne("Treinamentos.Domain.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_categories_categories_parent_category_id");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.Course", b =>
                {
                    b.HasOne("Treinamentos.Domain.Entities.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_courses_categories_category_id");

                    b.HasOne("Treinamentos.Domain.Entities.Company", "Company")
                        .WithMany("Courses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_courses_companies_company_id");

                    b.HasOne("Treinamentos.Domain.Entities.User", "Instructor")
                        .WithMany("CreatedCourses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_courses__users_instructor_id");

                    b.HasOne("Treinamentos.Domain.Entities.Category", "SubCategory")
                        .WithMany("SubCategoryCourses")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_courses_categories_sub_category_id");

                    b.Navigation("Category");

                    b.Navigation("Company");

                    b.Navigation("Instructor");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.CourseApproval", b =>
                {
                    b.HasOne("Treinamentos.Domain.Entities.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_course_approvals__users_admin_id");

                    b.HasOne("Treinamentos.Domain.Entities.Course", "Course")
                        .WithMany("Approvals")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_course_approvals_courses_course_id");

                    b.Navigation("Admin");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.CourseCompletion", b =>
                {
                    b.HasOne("Treinamentos.Domain.Entities.Course", "Course")
                        .WithMany("Completions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_course_completions_courses_course_id");

                    b.HasOne("Treinamentos.Domain.Entities.User", "User")
                        .WithMany("CourseCompletions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_course_completions__users_user_id");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.CourseDepartmentPermission", b =>
                {
                    b.HasOne("Treinamentos.Domain.Entities.Course", "Course")
                        .WithMany("DepartmentPermissions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_course_department_permissions_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.CourseUserPermission", b =>
                {
                    b.HasOne("Treinamentos.Domain.Entities.Course", "Course")
                        .WithMany("UserPermissions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_course_user_permissions_courses_course_id");

                    b.HasOne("Treinamentos.Domain.Entities.User", "User")
                        .WithMany("CourseUserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_course_user_permissions__users_user_id");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("Treinamentos.Domain.Entities.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_lessons_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.LessonAccess", b =>
                {
                    b.HasOne("Treinamentos.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonAccesses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_lesson_accesses_lessons_lesson_id");

                    b.HasOne("Treinamentos.Domain.Entities.User", "User")
                        .WithMany("LessonAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_lesson_accesses__users_user_id");

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.User", b =>
                {
                    b.HasOne("Treinamentos.Domain.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_users_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("Treinamentos.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.VideoProgress", b =>
                {
                    b.HasOne("Treinamentos.Domain.Entities.Lesson", "Lesson")
                        .WithMany("VideoProgresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_video_progresses_lessons_lesson_id");

                    b.HasOne("Treinamentos.Domain.Entities.User", "User")
                        .WithMany("VideoProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_video_progresses_users_user_id");

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.Category", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("SubCategories");

                    b.Navigation("SubCategoryCourses");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.Company", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.Course", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Completions");

                    b.Navigation("DepartmentPermissions");

                    b.Navigation("Lessons");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("LessonAccesses");

                    b.Navigation("VideoProgresses");
                });

            modelBuilder.Entity("Treinamentos.Domain.Entities.User", b =>
                {
                    b.Navigation("ActivationTokens");

                    b.Navigation("AuditLogs");

                    b.Navigation("CourseCompletions");

                    b.Navigation("CourseUserPermissions");

                    b.Navigation("CreatedCourses");

                    b.Navigation("LessonAccesses");

                    b.Navigation("Sessions");

                    b.Navigation("VideoProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
